// Auto-generated by build.sh - do not edit manually
// Keys injected via Vercel environment variables
window.BEEDOO_SVC = window.BEEDOO_SVC || '';
window.BEEDOO_SB  = window.BEEDOO_SB  || 'https://hqzpemfaljxcysyqssng.supabase.co';
window.BEEDOO_GKEY= window.BEEDOO_GKEY|| '';
